version: "3"
services:
  app:
    container_name: node
    restart: always
    build: .
    ports:
      - "80:3001"
    links:
      - mongo
  mongo:
    container_name: mongodb_test
    image: mongo
    ports:
      - "27017:27017"
